language: php

php:
  - '7.3'
  - '7.4'
  - '8.0'

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - XDEBUG_MODE=coverage
