/**
 * File generated by CMS
 * Use ModuleInstaller to trigger rebuild: $this->helper('react')->update()
 */

import * as React from './React';
import * as Mail from './Mail';

export default {React,Mail};