db:
    driver: pdo_mysql
    host: 127.0.0.1
    user: inventure
    password: 6Qq2fnX51zShHhDO
    dbname: inventure_beta
    charset: utf8
site:
    name: FRONT Inventure
    host: f.inventure.com.ua
mail:
  from:
    'no-reply@inventure.ua': 'InVenture Investment Portal'
  type:  smtp
  host: 'mail.ukraine.com.ua'
  port: 465
  encription: 'ssl'
  user: 'no-reply@inventure.ua'
  passwd: 'E0jo77mM'
i18n:
  locale: 'ru_RU.utf8'
  content:
    ru: 'ru_RU.utf8'
    en: 'en_US.utf8'
  cache: false
facebook:
  app_id: '160711107658620'
  app_secret: '0e479cef9fc6a75d9c7f6b8ef08a5d3b'