index:
    docinfo: extern
    dict: keywords
    mlock: 0
    morphology: 'stem_en, stem_ru, soundex'
    embedded_limit: 16K
    min_word_len: 1
    charset_type: utf-8
cron_time:
    delta: '*/5 * * * *'
    full: '14 2 * * *'
path:
    indexer: /usr/local/bin/indexer
    config_dir: /etc/sphinx/conf.d
    config: /etc/sphinx/sphinx.conf
    rotate: /etc/sphinx/rotate
dsn: 'mysql:unix_socket=/run/sphinxsearch/searchd.sql.sock;charset=utf8'
fields:
    - id
    - h1
    - published
    - short_text
    - attr
    - route
    - parent
    - views
    - rating
    - t1_class
sort:
    rel: 'WEIGHT() DESC'
    date: 'published DESC'
    category: 'route DESC, parent DESC, WEIGHT() DESC'
    view: 'views DESC'
    rating: 'rating DESC'
weights:
    h1: 4
    short_text: 2
